### PR TITLE
Make OPTIM copy loop faster and smaller.

### PR DESCRIPTION
**Pull request by pfusik**
I started playing with ZX0 today and found your project. Nice 6502 code!
I made a small optimization. I don't know how to determine cycles/byte - please update yourself or let me know.

I think this could lead to some further optimizations, as `pntr` is now basically just a bitwise negation of `offset`.

### CODE REVIEW

**Comment by pfusik** [comment]
> I think this could lead to some further optimizations, as pntr is now basically just a bitwise negation of offset.

Done in the second commit.
Can we modify the packer to do the negation for us?

**Comment by dmsc** [comment]
Hi!

Thank you for the optimization.

With this, the zx02-optim speed is 54.9 cycles/byte. 

But the zx102-optim does not pass all tests. I will investigate.

To run the tests, you need a Linux (or OSX) system, mads and my mini65-sim. In the tests folder you run `./test.sh files/*.bin` .

For the speed, I used a 7680 byte image file for the "conan" intro screen.

**Comment by dmsc** [comment]
I fixed the problem with the zx102-optim code and merged this.

Now, the `EOR #$FF` can be removed by adjusting the compressed format for 2 bytes less (and a little faster), but all the other decoders should be changed also.

Thanks again!

**Comment by dmsc** [comment]
Hi again!

Tried implementing the new format that allows to remove the `EOR #$FF`, but it did not work that well.

Problem is, the high bit of that bytes came from the ellias-gamma code, so instead of writing a '1' for the lowest offset values, I need to write a '2', this is two extra bits. This means that the code to read the ellias-gamma is slower (one more iteration) and that the compressed files are bigger.

Some sample test files I use:

The Prince Of Persia Atari game code, ZX0-x is 307 bytes bigger (0.8%):
```
TESTING FILE 'files/pop.bin', 40164 bytes.
 -> Compressing ZX0 based format: 22656 bytes
 -> Compressing ZX1 based format: 23150 bytes
 -> Compressing ZX0-x based format: 22963 bytes
 -> Decompress ZX02 FAST:  2977552 cycles, 74.1 cycles/byte:  TEST PASSED 
 -> Decompress ZX02 OPTIM: 2895607 cycles, 72.0 cycles/byte:  TEST PASSED 
 -> Decompress ZX02 SMALL: 4259583 cycles, 106.0 cycles/byte:  TEST PASSED 
 -> Decompress ZX02 -1 OPTIM: 2647398 cycles, 65.9 cycles/byte:  TEST PASSED 
 -> Decompress ZX02 -1 SMALL: 3530703 cycles, 87.9 cycles/byte:  TEST PASSED 
 -> Decompress ZX02 -x OPTIM: 2907500 cycles, 72.3 cycles/byte:  TEST PASSED 
```

The FastBasic compiler 21 bytes bigger:
```
TESTING FILE 'files/t3.bin', 3445 bytes.
 -> Compressing ZX0 based format: 2188 bytes
 -> Compressing ZX1 based format: 2282 bytes
 -> Compressing ZX0-x based format: 2209 bytes
 -> Decompress ZX02 FAST:   238731 cycles, 69.2 cycles/byte:  TEST PASSED 
 -> Decompress ZX02 OPTIM:  238280 cycles, 69.1 cycles/byte:  TEST PASSED 
 -> Decompress ZX02 SMALL:  350542 cycles, 101.7 cycles/byte:  TEST PASSED 
 -> Decompress ZX02 -1 OPTIM:  214713 cycles, 62.3 cycles/byte:  TEST PASSED 
 -> Decompress ZX02 -1 SMALL:  291855 cycles, 84.7 cycles/byte:  TEST PASSED 
 -> Decompress ZX02 -x OPTIM:  236905 cycles, 68.7 cycles/byte:  TEST PASSED 
```

I will think how this can be improved. 

Meanwhile, the experiment is at: https://github.com/dmsc/zx02/tree/experimental-skip-eor

You can use the '-x' option in the encoder to generate the compressed format, and use the https://github.com/dmsc/zx02/blob/experimental-skip-eor/6502/zx02-x-optim.asm to decode.

Have Fun!

**Comment by pfusik** [comment]
> To run the tests, you need a Linux (or OSX) system, mads and my mini65-sim. In the tests folder you run `./test.sh files/*.bin` .

Do you mean https://github.com/dmsc/mini65-sim ?

It works on Windows, except that a wildcard picks up just `blank.bin`:
image

I don't see where in `test.sh` do you handle wildcards?

**Comment by dmsc** [comment]
Hi!

> > To run the tests, you need a Linux (or OSX) system, mads and my mini65-sim. In the tests folder you run `./test.sh files/*.bin` .
> 
> Do you mean https://github.com/dmsc/mini65-sim ?
> 
Yes!

> It works on Windows, except that a wildcard picks up just `blank.bin`
> I don't see where in `test.sh` do you handle wildcards?

It does not, I was wrong, I simply iterate through all test files.

I will commit a change to the test script so that wildcards work.

Have Fun!

**Comment by dmsc** [comment]
Done!

Also, here is the "conan" test file that I used to test the speed.
[conan.zip](https://github.com/user-attachments/files/16663568/conan.zip)

**Comment by dmsc** [comment]
🤣

I took the sample from an Atariage thread

Have Fun!

**Pull request merged**
